In [4]:
import numpy as np


In [5]:
x = np.array([[1,2], [13, 4],[5,6]], dtype=np.float32)
x


array([[ 1.,  2.],
       [13.,  4.],
       [ 5.,  6.]], dtype=float32)

In [6]:
x.shape

(3, 2)

In [7]:
y= 2*x
y

array([[ 2.,  4.],
       [26.,  8.],
       [10., 12.]], dtype=float32)

In [8]:
for i in range(x.shape[0]):
    
    print(x[i])

[1. 2.]
[13.  4.]
[5. 6.]


In [9]:
for j in range(y.shape[0]):
    print(y[j])

[2. 4.]
[26.  8.]
[10. 12.]


In [10]:
discts = np.zeros((3,3))
for i in range(x.shape[0]):
    for j in range(y.shape[0]):
        x_img = x[i]
        y_img = y[j]
        discts[i,j] = np.sqrt(np.sum(np.square(x_img - y_img)))

In [11]:
print (discts)

# k = 2
# z= np.argsort(discts[0])[:k]
# zz=discts[z]
# values, counts = np.unique(zz, return_counts=True)
# print (values, counts)
# a= counts.argsort()
# print(a)

[[ 2.23606801 25.70992088 13.45362377]
 [11.         13.60147095  8.54400349]
 [ 3.60555124 21.0950222   7.81024981]]


In [12]:
discts = np.zeros((3,3))
for i in range(x.shape[0]):
    arr=x[i]-y
    discts[i, :] = np.sqrt(np.sum(np.square(arr),axis=1))
print(discts)

[[ 2.23606801 25.70992088 13.45362377]
 [11.         13.60147095  8.54400349]
 [ 3.60555124 21.0950222   7.81024981]]


In [13]:
discts = np.zeros((3,3))
for i in range(x.shape[0]):
    print(x[i])
    print(y)
    arr=x[i]-y
    print(arr)
    discts[i, :] = np.sqrt(np.sum(np.square(arr),axis=1))
print(discts)

[1. 2.]
[[ 2.  4.]
 [26.  8.]
 [10. 12.]]
[[ -1.  -2.]
 [-25.  -6.]
 [ -9. -10.]]
[13.  4.]
[[ 2.  4.]
 [26.  8.]
 [10. 12.]]
[[ 11.   0.]
 [-13.  -4.]
 [  3.  -8.]]
[5. 6.]
[[ 2.  4.]
 [26.  8.]
 [10. 12.]]
[[  3.   2.]
 [-21.  -2.]
 [ -5.  -6.]]
[[ 2.23606801 25.70992088 13.45362377]
 [11.         13.60147095  8.54400349]
 [ 3.60555124 21.0950222   7.81024981]]


In [14]:
discts = np.zeros((3,3))
arr = np.multiply(np.subtract(x[0:3],y),np.subtract(x,y[0:3]))
print(arr)

[[  1.   4.]
 [169.  16.]
 [ 25.  36.]]


In [20]:
x = np.arange(9.0)
print(x)
x_train_fold = np.split(x,3)
print(x_train_fold)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]
