In [1]:
import numpy as np


In [2]:
x = np.array([[1,2], [13, 4],[5,6]], dtype=np.float32)
x


array([[ 1.,  2.],
       [13.,  4.],
       [ 5.,  6.]], dtype=float32)

In [3]:
x.shape

(3, 2)

In [4]:
y= 2*x
y

array([[ 2.,  4.],
       [26.,  8.],
       [10., 12.]], dtype=float32)

In [5]:
for i in range(x.shape[0]):
    
    print(x[i])

[1. 2.]
[13.  4.]
[5. 6.]


In [6]:
for j in range(y.shape[0]):
    print(y[j])

[2. 4.]
[26.  8.]
[10. 12.]


In [7]:
discts = np.zeros((3,3))
for i in range(x.shape[0]):
    for j in range(y.shape[0]):
        x_img = x[i]
        y_img = y[j]
        discts[i,j] = np.sqrt(np.sum(np.square(x_img - y_img)))

In [8]:
print (discts)

# k = 2
# z= np.argsort(discts[0])[:k]
# zz=discts[z]
# values, counts = np.unique(zz, return_counts=True)
# print (values, counts)
# a= counts.argsort()
# print(a)

[[ 2.23606801 25.70992088 13.45362377]
 [11.         13.60147095  8.54400349]
 [ 3.60555124 21.0950222   7.81024981]]


In [9]:
discts = np.zeros((3,3))
for i in range(x.shape[0]):
    arr=x[i]-y
    discts[i, :] = np.sqrt(np.sum(np.square(arr),axis=1))
print(discts)

[[ 2.23606801 25.70992088 13.45362377]
 [11.         13.60147095  8.54400349]
 [ 3.60555124 21.0950222   7.81024981]]


In [10]:
discts = np.zeros((3,3))
for i in range(x.shape[0]):
    print(x[i])
    print(y)
    arr=x[i]-y
    print(arr)
    discts[i, :] = np.sqrt(np.sum(np.square(arr),axis=1))
print(discts)

[1. 2.]
[[ 2.  4.]
 [26.  8.]
 [10. 12.]]
[[ -1.  -2.]
 [-25.  -6.]
 [ -9. -10.]]
[13.  4.]
[[ 2.  4.]
 [26.  8.]
 [10. 12.]]
[[ 11.   0.]
 [-13.  -4.]
 [  3.  -8.]]
[5. 6.]
[[ 2.  4.]
 [26.  8.]
 [10. 12.]]
[[  3.   2.]
 [-21.  -2.]
 [ -5.  -6.]]
[[ 2.23606801 25.70992088 13.45362377]
 [11.         13.60147095  8.54400349]
 [ 3.60555124 21.0950222   7.81024981]]


In [11]:
discts = np.zeros((3,3))
arr = np.multiply(np.subtract(x[0:3],y),np.subtract(x,y[0:3]))
print(arr)

[[  1.   4.]
 [169.  16.]
 [ 25.  36.]]


In [12]:
x = np.arange(9.0)
print(x)
x_train_fold = np.split(x,3)
print(x_train_fold)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]


In [41]:
# train
a = 2
b = 4
c = 10
y = 100

step_size = 0.0001
for i in range(200):
    ab = (a + b)
    x = ab * c

    diff = (x - y)
    loss = diff ** 2

    loss_delta = 1
    diff_delta = 2 * diff
    x_delta = diff_delta
    c_delta =  ab * x_delta
    ab_delta = c * x_delta
    a_delta = ab_delta
    b_delta = ab_delta


    a += -step_size * a_delta
    b += -step_size * b_delta
    c += -step_size * c_delta

    if i % 1 == 0:
        print('i=',i,'loss', loss)

print(a,b,c, (a+b)*c)

i= 0 loss 1600
i= 1 loss 1451.9392026624
i= 2 loss 1315.448504566532
i= 3 loss 1189.8949898298238
i= 4 loss 1074.6492740696422
i= 5 loss 969.0887171098545
i= 6 loss 872.6006543801751
i= 7 loss 784.5855180926369
i= 8 loss 704.4597457502421
i= 9 loss 631.6583987378829
i= 10 loss 565.6374370551855
i= 11 loss 505.8756172024625
i= 12 loss 451.8759985026559
i= 13 loss 403.16705856235865
i= 14 loss 359.30343111055487
i= 15 loss 319.8662891907373
i= 16 loss 284.46340380231493
i= 17 loss 252.72891284265305
i= 18 loss 224.32283788917897
i= 19 loss 198.9303873020132
i= 20 loss 176.26108364549088
i= 21 loss 156.04775183382958
i= 22 loss 138.045401990892
i= 23 loss 122.03003803438065
i= 24 loss 107.7974196734324
i= 25 loss 95.16180203109943
i= 26 loss 83.95467361911494
i= 27 loss 74.02351001703741
i= 28 loss 65.23055742614054
i= 29 loss 57.451657338328836
i= 30 loss 50.575120917329066
i= 31 loss 44.50065935055268
i= 32 loss 39.138374397853426
i= 33 loss 34.40781162946582
i= 34 loss 30.2370773933554